### ISSUE TITLE
LoRa HAT doesn't signal back after RX1/2 windows end w/o receiving downlink packets

### ISSUE THREAD

**Issue by dynaxis** [wklenk/lmic-rpi-lora-gps-hat#5]
I'm trying the `transmit` example in a US915 setting. The node joins my network successfully, but after a TX, the node doesn't get notified even after RX1/2 windows are all expired. To my understanding, the radio should issue an interrupt after RX1/2 windows are all passed, but it doesn't seems doing so.

According to my analysis, RX1 doesn't get back to LMIC when nothing is received.

So, sometimes the node successfully joins, and though it stuck there, the data is successfully received by my network server as follows:
```
pi@raspberrypi:~/lmic-rpi-lora-gps-hat-master/examples/transmit $ sudo build/transmit.out
000000000 HAL: Initializing ...
000000003 HAL: Detected SX1276 radio module.
000000003 HAL: Set radio RST pin to 0x00
000000003 HAL: Wait until 000000004 ms
000000007 HAL: Set radio RST pin to 0x02
000000008 HAL: Wait until 000000013 ms
000000021 HAL: Receiving ...
000000032 Debug: Initializing
000000033 Debug: JOINING
000000033 freq: 902300000...
000000034 Debug: EV_TXSTART
000000035 HAL: Sending ...
000005096 HAL: Receiving ...
000005097 HAL: Wait until 000005098 ms
000005111 Debug: JOINED
000005111 Debug: Label 'netid = ' value 0x0
000005112 freq: 902300000...
000005112 Debug: EV_TXSTART
000005113 HAL: Sending ...
000006158 HAL: Receiving ...
000006158 HAL: Wait until 000006160 ms
```

But in many cases, it just stuck while joining as follows:
```
pi@raspberrypi:~/lmic-rpi-lora-gps-hat-master/examples/transmit $ sudo build/transmit.out
000000000 HAL: Initializing ...
000000003 HAL: Detected SX1276 radio module.
000000003 HAL: Set radio RST pin to 0x00
000000003 HAL: Wait until 000000004 ms
000000008 HAL: Set radio RST pin to 0x02
000000008 HAL: Wait until 000000013 ms
000000013 HAL: Receiving ...
000000027 Debug: Initializing
000000027 Debug: JOINING
000000027 freq: 902300000...
000000027 Debug: EV_TXSTART
000000028 HAL: Sending ...
000005089 HAL: Receiving ...
000005089 HAL: Wait until 000005090 ms
```

In the latter case, no data is received by my network server.

Is there any clue?

I'm using RHF0M301 w/ RPi3 as my gateway, this (https://github.com/gotthardp/lorawan-server) as my network server, and the Dragino LoRa GPS HAT + RPi3 for my node.

**Comment by wklenk** [comment]
Hi Kim,

unfortunately it seems that I have removed debug messages from the code that indicate a „timeout“. Maybe that would have been helpful in this case. If you like to add one, then the place would be in lora_gps_hat/hal.c, right after the call to 

int rc = gpioWaitForInterrupt(BCM_PIN_DIO, 3, sleep_interval_ms);

If this returns a rc == 0, then this indicates that none of the 3 input lines went „high“ in the given sleep_interval_ms time.

I think there are 2 issues:

Issue #1: „transfer“ application
Without having checked, I think the LMIC example application „transfer“ does not really care about unsuccessful „join“ operations. I think it just stucks. The example application „join“ is behaves better in this way: If it doesn’t receive anything from the gateway in time, it just retries with different frequencies and spreading factors. So, I think you should try out what happens if you use „join“ instead.

Issue #2: Gateway not covering all frequencies

File /lmic/lmic.c:

The LMIC 1.6 stack randomly chooses one of six frequencies to send the "join" message to the network. Tesing with a Kerlink IoT Station, only the following frequencies worked: 868.1 868.3 868.5 MHz The following default frequency did not work: 864.1 864.3 864.5 For this reason, I modified the code to only randomly choose between the three working join frequencies.

So, the LMIC stack randomly chooses one of six frequencies, and some gateways are only able to deal with ONE frequency. So there is a chance of 1 out of 6 that your „join“ operation is successful. So you need to find out if you have a „single channel gateway“ or a „real“ LoRaWAN conforming gateway. As I wrote, I also had some issues with a Kerlink IoT Station, as it only died support 3 of 6 join frequencies. I needed to go into the LMIC original code in lmic/lmic.c and fix this. If you have a single channel gateway, you could also make sure that you have 6 identical frequencies there, to get it working.

I hope this advice helped. Please let me know what you found out.

Best regards,
Wolfgang

**Comment by dynaxis** [comment]
Thank you, Wolfgang.

I've already tweaked some of LMIC to accommodate the limited number of channels supported by the gateway. And also looking into my network server to check if it selects the downlink frequency in the way I think it should work.

I guessed there was something different in US915 setting making the RX timeout not raised. But I looked closely into LMIC codebase, and it doesn't seems so. Now I'm suspecting the HAT has some defects.

I'm closing this issue. Thanks again.

If I find something useful to others, then will leave a note here.

**Comment by dynaxis** [comment]
FYI.

As I suspected, there is no wiring for DIO1/2 on my HAT. That's why RX timeout is missing while RX done is properly issued. My HAT is of revision 1.0 and its schematic shows that there are no wirings for both DIO1 and 2 (https://github.com/dragino/Lora/blob/master/Lora_GPS%20HAT/v1.0/Lora%20GPS%20%20HAT%20for%20RPi%20v1.0.pdf). According to the schematics of more recent revisions of the HAT, recent ones don't have the same problem.

I saw the interrupt being raised when the missing connection is made (by hand) but haven't had enough time yet to get the whole system work as expected. Anyway, I'm fairly sure there is no further problem at all.

Also I've found my network server needs some customization in selecting downlink channels to accommodate the limited number of channels supported by my gateway. This is especially important due to my use of US915 where downlinks use separate channels from uplinks.
